# This starter workflow is for a CMake project running on multiple platforms. There is a different starter workflow if you just want a single platform.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-single-platform.yml
name: CMake on multiple platforms

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  
  conda_check:
    runs-on: macos-15-intel
    steps:
    - uses: actions/checkout@v3

    - name: Checkout submodules # checkout rest
      shell: bash
      run: |
        auth_header="$(git config --local --get http.https://github.com/.extraheader)"
        git submodule sync --recursive
        git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1

    - name: set path
      run: echo "/opt/mambaforge/bin" >> $GITHUB_PATH

    - name: show dir
      run: ls .

    - name: build sdist
      run: pip install setuptools && python setup.py sdist && mkdir tmp && cd tmp && tar -xf ../dist/pygrgl-2.10.tar.gz && cd ..


    - name: Fetch conda install script
      run: |
        wget https://raw.githubusercontent.com/bioconda/bioconda-common/master/{install-and-set-up-conda,configure-conda,common}.sh

    - name: Set up bioconda-utils
      run: bash install-and-set-up-conda.sh

    # This script can be used to reconfigure conda to use the right channel setup.
    - name: Configure conda
      run: bash configure-conda.sh

    - name: Build and Test
      env:
        OSTYPE: "darwin"
        CI: "true"
      run: |
        set -e
        eval "$(conda shell.bash hook)"
        conda activate bioconda

        # Sets up OSX SDK
        run_conda_forge_build_setup

        cd bioc_recip_tmp && bioconda-utils build --packages pygrgl
